---
-
  hosts: control
  become: true
  tasks:


  - name: Remove old files srv
    file:
      path: /srv
      state: absent


  - name: Remove old files in html
    file:
      path: /var/www/html/
      state: absent
  -
    git:
        repo: https://github.com/saishiva0603/project4.git
        dest: /srv

  - name: Move files to html dir
    command: mv /srv /var/www/html
